---
- name: installing gnupg2
  apt:
    name: gnupg2
    state: present

- name: adding apt key https://packages.grafana.com/gpg.key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: adding apt repostiroy deb https://packages.grafana.com/oss/deb stable main
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main

- name: installing grafana
  apt:
    name: grafana
    state: present
    update_cache: true

- name: enabling and starting grafana service
  systemd:
    name: grafana-server
    state: started
    enabled: yes
